name: CI workflow
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]
        os: [ubuntu-latest] # disabled windows-latest until we figure out a way to use docker in it
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm install --ignore-scripts
    - name: Test
      run: npm run test
